// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke, Channel } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

export const faders = {
  set(channel: number, value: number): Promise<null> {
    return invoke("set", { channel, value });
  },

  level(channel: number): Promise<number> {
    return invoke("level", { channel });
  },

  /** @throws {SaveError} */
  saveScene(path: string): Promise<null> {
    return invoke("save_scene", { path });
  },

  fade(channel: number, levels: Channel<number>): Promise<null> {
    return invoke("fade", { channel, levels });
  },
};

export type SaveError = { type: "io"; message: string };

export type FaderEvent = { type: "changed"; channel: number; value: number };

export const events = {
  fader: {
    listen(callback: (event: FaderEvent) => void): Promise<() => void> {
      return listen<{ channel: number; value: number }>("fader:changed", (event) => callback({ type: "changed", ...event.payload }));
    },
  },
};

