// faders: the ttipc example app, TS half.
//
// ./bindings.ts is generated by ttipc from the Faders trait and the
// FaderEvent enum; the Rust-side binding test regenerates and checks it
// for drift. The whole client is generated -- save_scene included.

import { Channel } from "@tauri-apps/api/core";
import { faders, events, type SaveError } from "./bindings";

const CHANNELS = 8;

const desk = document.querySelector<HTMLDivElement>("#desk")!;
const sliders: HTMLInputElement[] = [];

// The virtual rig: stands in for DMX hardware until the lux port. Each
// swatch shows a channel level as brightness, updated from FaderEvent
// (the ttipc of Rust's canonical state, broadcast to every listener)
// or, during a fade, from that call's own Channel (a request-scoped
// stream to the one caller) -- never optimistically from input. Swatches
// lagging or diverging from the sliders under fast scrubbing means the
// roundtrip is broken.
const rig = document.querySelector<HTMLDivElement>("#rig")!;
const swatches: HTMLDivElement[] = [];

function paint(channel: number, value: number) {
  swatches[channel].style.background = `rgb(${value}, ${value}, ${value})`;
}

for (let channel = 0; channel < CHANNELS; channel++) {
  const slider = document.createElement("input");
  slider.type = "range";
  slider.min = "0";
  slider.max = "255";
  // Args are checked against the Deserialize phase of the Rust types.
  // The await is the wire, not the executor: the Rust side runs sync on
  // the main thread.
  slider.addEventListener("input", () => {
    void faders.set(channel, Number(slider.value));
  });
  desk.append(slider);
  sliders.push(slider);

  const swatch = document.createElement("div");
  swatch.style.cssText = "width: 32px; height: 32px; background: rgb(0, 0, 0)";
  rig.append(swatch);
  swatches.push(swatch);
}

// One listener registry per domain channel (the hardware -> UI
// direction). The Event derive owns the wire shape on both sides, so
// payloads arrive pre-narrowed to the Serialize phase: no casts here.
void events.fader.listen((e) => {
  if (e.type === "changed") {
    sliders[e.channel].value = String(e.value);
    paint(e.channel, e.value);
  }
});

// Rust owns the canonical levels; the UI is a mirror that re-reads.
for (let channel = 0; channel < CHANNELS; channel++) {
  void faders.level(channel).then((v) => {
    sliders[channel].value = String(v);
    paint(channel, v);
  });
}

document
  .querySelector<HTMLButtonElement>("#fade")!
  .addEventListener("click", () => {
    // A request-scoped Channel: the fade streams channel 0's levels back
    // to this one caller (distinct from the fader event broadcast), and
    // each frame paints the swatch. The JS Channel serializes to its id
    // on the wire, so it is passed like any argument.
    const levels = new Channel<number>();
    levels.onmessage = (value) => paint(0, value);
    void faders.fade(0, levels);
  });

document
  .querySelector<HTMLButtonElement>("#save")!
  .addEventListener("click", () => {
    // A ttipc async procedure; it rejects with the typed SaveError
    // union, so the catch branches on err.type instead of a stringly
    // guess.
    faders.saveScene("scene.bin").catch((err: SaveError) => {
      console.error(`save failed (${err.type}): ${err.message}`);
    });
  });
